
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: abhishekf5/ultimate-cicd
  SONAR_URL: http://54.91.149.44:9000
  GIT_REPO_NAME: Jenkins-Zero-To-Hero
  GIT_USER_NAME: brams898

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test
        run: |
          ls -ltr
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && mvn clean package

      - name: Static Code Analysis
        run: |
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && \
          mvn sonar:sonar -Dsonar.login=${{ secrets.SONAR_AUTH_TOKEN }} -Dsonar.host.url=${{ env.SONAR_URL }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          cd java-maven-sonar-argocd-helm-k8s/spring-boot-app && \
          docker build -t ${{ env.DOCKER_IMAGE }}:${{ github.run_number }} . && \
          docker push ${{ env.DOCKER_IMAGE }}:${{ github.run_number }}

      - name: Update Deployment File
        run: |
          git config user.email "abhishek.xyz@gmail.com"
          git config user.name "Abhishek Veeramalla"
          sed -i "s/replaceImageTag/${{ github.run_number }}/g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
          git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
          git commit -m "Update deployment image to version ${{ github.run_number }}"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.GIT_USER_NAME }}/${{ env.GIT_REPO_NAME }}.git HEAD:main
